#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KoshelnykAndroidTestTask.Resource", IsApplication=true)]

namespace KoshelnykAndroidTestTask
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int myAnimation = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_compat_inset_shadow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_default_elevation = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_default_radius = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anim = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b_g = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int driving_report = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int header = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int help = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int i_c_ebtn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int login_image = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int messaging_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int nav_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int p_o_i_btn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int select_journey_btn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settingbtn = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int traffilog_logo_1024_x_3592 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vhicle_check_btn = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000e
			public const int AccelarationCount = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int AccelarationPer = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int BrakesCount = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int BrakesPer = 2131296275;
			
			// aapt resource value: 0x7f090009
			public const int DriverId = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int DriverStatus = 2131296266;
			
			// aapt resource value: 0x7f090014
			public const int GradeType = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int GradeTypeDescription = 2131296274;
			
			// aapt resource value: 0x7f09000c
			public const int SpeedCount = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int SpeedPer = 2131296267;
			
			// aapt resource value: 0x7f090015
			public const int Tip = 2131296277;
			
			// aapt resource value: 0x7f09000f
			public const int TurnsPer = 2131296271;
			
			// aapt resource value: 0x7f090022
			public const int animIV = 2131296290;
			
			// aapt resource value: 0x7f09001c
			public const int driving_ReportBn = 2131296284;
			
			// aapt resource value: 0x7f090021
			public const int forgotYourPassword = 2131296289;
			
			// aapt resource value: 0x7f090001
			public const int helpBn = 2131296257;
			
			// aapt resource value: 0x7f090019
			public const int i_c_eBn = 2131296281;
			
			// aapt resource value: 0x7f09001d
			public const int imageView1 = 2131296285;
			
			// aapt resource value: 0x7f090004
			public const int isOnline = 2131296260;
			
			// aapt resource value: 0x7f090018
			public const int journeySelectionBn = 2131296280;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout2 = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int linearLayout4 = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout5 = 2131296262;
			
			// aapt resource value: 0x7f090020
			public const int loginBn = 2131296288;
			
			// aapt resource value: 0x7f09001e
			public const int loginET = 2131296286;
			
			// aapt resource value: 0x7f090024
			public const int messageTV = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int messagesLV = 2131296291;
			
			// aapt resource value: 0x7f090017
			public const int messagingBn = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int navigBn = 2131296278;
			
			// aapt resource value: 0x7f09001f
			public const int passwordET = 2131296287;
			
			// aapt resource value: 0x7f09001a
			public const int pointOfInterestBn = 2131296282;
			
			// aapt resource value: 0x7f090002
			public const int settingBn = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int textView1 = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int textView2 = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int turnsCountTV = 2131296269;
			
			// aapt resource value: 0x7f09001b
			public const int vehicleCheckBn = 2131296283;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DriverReport = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Messaging = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int VehicleCheck = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080007
			public const int AllRightsReserved = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int forgotYourPassword = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int goodMorning = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int login = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int loginHint = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int online = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int passwordHint = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Base_CardView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CardView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int CardView_Dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CardView_Light = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
